// Seed file for smokedope2016 song database — 92 unique tracks across all releases.
import { PrismaClient } from '@prisma/client';

const prisma = new PrismaClient();

// Album cover URLs
const covers = {
  smokeshop: 'https://f4.bcbits.com/img/a2308272733_5.jpg',
  xtc: 'https://f4.bcbits.com/img/a1533603834_5.jpg',
  bando: 'https://f4.bcbits.com/img/a0327420914_5.jpg',
  smokeshop2: 'https://cdn-images.dzcdn.net/images/cover/caeae81dfc4833c782cc96b8b25900fa/640x640-000000-80-0-0.jpg',
  album2016: 'https://coverartarchive.org/release/ef7c71f5-c848-4f84-a3bd-c72377b0dbdf/38943907743-500.jpg',
  comeup: 'https://cdn-images.dzcdn.net/images/cover/23fa0725c20a28ef2dfdf6d173792099/640x640-000000-80-0-0.jpg',
  peak: 'https://cdn-images.dzcdn.net/images/cover/b004c8c39c4f7aef180e34dbe59cde18/640x640-000000-80-0-0.jpg',
  comedown: 'https://cdn-images.dzcdn.net/images/cover/1250897f68ebecf3f2d292b8cdc0438a/640x640-000000-80-0-0.jpg',
};

function slug(title: string): string {
  return title
    .toLowerCase()
    .replace(/[^a-z0-9\s-]/g, '')
    .trim()
    .replace(/\s+/g, '-')
    .replace(/-+/g, '-');
}

type SeedSong = {
  title: string;
  features: string;
  album: string;
  year: number;
  releaseDate: string;
  durationSecs: number;
  albumCover: string;
  description: string;
  singleCover?: string | null;
};

const songs: SeedSong[] = [
  // ─── SMOKESHOP (Sep 11, 2022) ────────────────────────────────────────────
  {
    title: 'INTRO',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 153,
    albumCover: covers.smokeshop,
    description: 'The opener to SMOKESHOP. Sets the hazy, lo-fi tone — sparse production and attitude before the tape fully kicks in.',
  },
  {
    title: 'SMOKESHOP',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 117,
    albumCover: covers.smokeshop,
    description: 'Title track. The manifesto moment: smoke, scarcity, and a coded world only the right people know how to read.',
  },
  {
    title: 'JUNGLE MAGZ',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 122,
    albumCover: covers.smokeshop,
    description: 'Raw energy over a grimy beat. JUNGLE MAGZ is where the aggression of the debut leaks through the cracks.',
  },
  {
    title: 'LOAN',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 117,
    albumCover: covers.smokeshop,
    description: 'Short and blunt. LOAN captures the grind mentality early in the catalogue — everything costs something.',
  },
  {
    title: 'L.L BEANZ',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 151,
    albumCover: covers.smokeshop,
    description: 'A mid-tape breather with coded references and throwback energy. Scam rap DNA in the delivery.',
  },
  {
    title: 'XBOX 720',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 159,
    albumCover: covers.smokeshop,
    description: 'Nostalgic title, sharp execution. XBOX 720 rides a chopped loop while flexing on a generation that remembers the era.',
  },
  {
    title: '2006',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 93,
    albumCover: covers.smokeshop,
    description: 'The shortest cut on SMOKESHOP. A time capsule — early 2000s reference points folded into a minute-and-a-half.',
  },
  {
    title: 'HUSTLENOMICON',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 135,
    albumCover: covers.smokeshop,
    description: 'The playbook in song form. HUSTLENOMICON is the ideology behind the brand put to tape.',
  },
  {
    title: 'RHINO PILL',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 145,
    albumCover: covers.smokeshop,
    description: 'Deep in the SMOKESHOP run — energy still locked in, beat stays muted. The kind of track that rewards repeat listens.',
  },
  {
    title: '123456',
    features: '[]',
    album: 'SMOKESHOP',
    year: 2022,
    releaseDate: '2022-09-11',
    durationSecs: 110,
    albumCover: covers.smokeshop,
    description: 'Closing out the debut. 123456 ends the tape the same way it started: direct, unfiltered, and no features needed.',
  },

  // ─── XTC (Nov 27, 2022) ──────────────────────────────────────────────────
  {
    title: 'BOOTED',
    features: '[]',
    album: 'XTC',
    year: 2022,
    releaseDate: '2022-11-27',
    durationSecs: 170,
    albumCover: covers.xtc,
    description: 'Opening XTC with a statement. The beat hits different than SMOKESHOP — more atmospheric, same cold confidence.',
  },
  {
    title: 'ON GOD',
    features: '[]',
    album: 'XTC',
    year: 2022,
    releaseDate: '2022-11-27',
    durationSecs: 152,
    albumCover: covers.xtc,
    description: 'Affirmations with teeth. ON GOD is smokedope asserting the vision before the larger audience arrived.',
  },
  {
    title: 'ZOEY 101',
    features: '[]',
    album: 'XTC',
    year: 2022,
    releaseDate: '2022-11-27',
    durationSecs: 195,
    albumCover: covers.xtc,
    description: 'Y2K nostalgia as aesthetic fuel. ZOEY 101 name-drops an era to place smokedope\'s sound in a very specific cultural timeline.',
  },
  {
    title: 'IM NOT GOD BUT I WISH I WAS',
    features: '["Joeyy"]',
    album: 'XTC',
    year: 2022,
    releaseDate: '2022-11-27',
    durationSecs: 185,
    albumCover: covers.xtc,
    description: 'The breakout from XTC. Joeyy\'s feature turns this into a cloud rap classic — dreamy, detached, and instantly quotable. 30M+ streams.',
  },
  {
    title: 'KNICKS IN 2013',
    features: '[]',
    album: 'XTC',
    year: 2022,
    releaseDate: '2022-11-27',
    durationSecs: 174,
    albumCover: covers.xtc,
    description: 'Closing XTC with another era reference. The Knicks in 2013 — a team on the edge of something, never quite arriving.',
  },

  // ─── BANDO (Jan 1, 2023) ─────────────────────────────────────────────────
  {
    title: 'BUMPSTOCK',
    features: '[]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 238,
    albumCover: covers.bando,
    description: 'The longest track on BANDO. BUMPSTOCK sprawls out over a heavy beat — deliberate, unhurried, loaded.',
  },
  {
    title: 'BANDO',
    features: '[]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 112,
    albumCover: covers.bando,
    description: 'Title track, under two minutes. The bando is the setting, the mindset, the whole thesis of the project compressed.',
  },
  {
    title: 'TAHOE',
    features: '[]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 130,
    albumCover: covers.bando,
    description: 'Road music. TAHOE pulls in imagery of movement, status, and the open highway between the trap and the next move.',
  },
  {
    title: 'AIRSTREAKS',
    features: '["ELCAMMGGUOD"]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 110,
    albumCover: covers.bando,
    description: 'Sneaker flexing over a skeletal beat. AIRSTREAKS with ELCAMMGGUOD is quick, energetic, and footwear-obsessed.',
  },
  {
    title: 'RUDY',
    features: '[]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 220,
    albumCover: covers.bando,
    description: 'One of the longer cuts on BANDO. RUDY moves slow and purposeful, like the tape is in no rush to explain itself.',
  },
  {
    title: 'LAG SWITCH',
    features: '["DR. TANK"]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 107,
    albumCover: covers.bando,
    description: 'Under two minutes with DR. TANK. Gaming slang as metaphor — freezing the opponent, gaining the advantage.',
  },
  {
    title: 'ON MY LEVEL',
    features: '[]',
    album: 'BANDO',
    year: 2023,
    releaseDate: '2023-01-01',
    durationSecs: 188,
    albumCover: covers.bando,
    description: 'Closing BANDO with a status check. ON MY LEVEL is the benchmark — where is everyone else relative to where he\'s at.',
  },

  // ─── SMOKESHOP 2 (Jun 2, 2023) ───────────────────────────────────────────
  {
    title: 'GHILLIE',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 161,
    albumCover: covers.smokeshop2,
    description: 'Opening SMOKESHOP 2 in camouflage. GHILLIE is the most-listened track on the project — blending in while standing out.',
  },
  {
    title: 'RED RING',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 165,
    albumCover: covers.smokeshop2,
    description: 'Xbox error energy. RED RING of death as a metaphor — crashing out while everything was supposed to work.',
  },
  {
    title: 'TRIPLE',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 190,
    albumCover: covers.smokeshop2,
    description: 'The longest track on SMOKESHOP 2. TRIPLE stacks references three deep — trap, nostalgia, and niche internet culture.',
  },
  {
    title: 'THIRSTY',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 144,
    albumCover: covers.smokeshop2,
    description: 'Energy that doesn\'t apologize for wanting more. THIRSTY is hunger made sonic.',
  },
  {
    title: 'LEBRON 9s',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 201,
    albumCover: covers.smokeshop2,
    description: 'Sneaker archival as status symbol. The LeBron 9 is a specific era, a specific colorway in mind — collectible energy.',
  },
  {
    title: 'INDEPENDENT',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 139,
    albumCover: covers.smokeshop2,
    description: 'No label, no co-sign. INDEPENDENT is the mission statement buried in the middle of the sequel.',
  },
  {
    title: 'CHAINZ',
    features: '["Dr Tank"]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 157,
    albumCover: covers.smokeshop2,
    description: 'Jewelry flexing with Dr Tank. CHAINZ keeps the SMOKESHOP 2 energy tight — short, visual, stacked.',
  },
  {
    title: 'UAV',
    features: '[]',
    album: 'SMOKESHOP 2',
    year: 2023,
    releaseDate: '2023-06-02',
    durationSecs: 138,
    albumCover: covers.smokeshop2,
    description: 'Surveillance-era closer. UAV ends the project with precision — aerial perspective, watching from above.',
  },

  // ─── 2016 (Dec 1, 2023) ──────────────────────────────────────────────────
  {
    title: 'On My Roof',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 133,
    albumCover: covers.album2016,
    description: 'Elevated perspective. On My Roof opens the 2016 album from a literal and metaphorical high point — above the noise.',
  },
  {
    title: 'Nike',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 156,
    albumCover: covers.album2016,
    description: 'Swoosh energy. Nike as identity marker, cultural shorthand for doing it — just doing it with no explanation required.',
  },
  {
    title: '2016',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 242,
    albumCover: covers.album2016,
    description: 'The title track. At four minutes it\'s the deepest cut on the project — using the year as a lens to interrogate who he was becoming.',
  },
  {
    title: 'Damian Lillard',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 179,
    albumCover: covers.album2016,
    description: 'Dame Time. Lillard as model for clutch performance and loyalty to the process, even when the city stops watching.',
  },
  {
    title: 'Know Dat',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 118,
    albumCover: covers.album2016,
    description: 'Under two minutes, no wasted space. Know Dat is the track that hit 10M+ streams — instant, sticky, undeniable.',
  },
  {
    title: 'Mobile',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 214,
    albumCover: covers.album2016,
    description: 'Moving through. Mobile stretches out the 2016 album into more contemplative territory — phone as lifeline, city as backdrop.',
  },
  {
    title: 'Poppy',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 200,
    albumCover: covers.album2016,
    description: 'Soft exterior, sharp interior. Poppy is deceptively melodic — the sweetest-sounding track on a project full of coded language.',
  },
  {
    title: 'Trill',
    features: '[]',
    album: '2016',
    year: 2023,
    releaseDate: '2023-12-01',
    durationSecs: 208,
    albumCover: covers.album2016,
    description: 'Closing 2016 with an authenticity statement. Trill is the final word — everything before this was real.',
  },

  // ─── THE COMEUP (May 24, 2024) ───────────────────────────────────────────
  {
    title: 'Drank',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 120,
    albumCover: covers.comeup,
    description: 'THE COMEUP opener. Drank sets the lean-and-slow aesthetic of the project — before anything pops, there\'s the come-up.',
  },
  {
    title: 'White Owls',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 197,
    albumCover: covers.comeup,
    description: 'The highest-streamed track on THE COMEUP at 18.9M. White Owls floats over a dreamy loop — the cigar becomes a symbol for waiting, building, and watching.',
  },
  {
    title: 'Glock',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 205,
    albumCover: covers.comeup,
    description: 'Hard pivot from White Owls. Glock brings the edge back — protection, paranoia, and presence.',
  },
  {
    title: 'Merch',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 157,
    albumCover: covers.comeup,
    description: 'Brand before the brand blew up. Merch is about identity in clothing — wearing the aesthetic before anyone was buying.',
  },
  {
    title: 'No Water',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 126,
    albumCover: covers.comeup,
    description: 'Quick and suffocating. No Water is a dry, claustrophobic two minutes — pressure from all sides.',
  },
  {
    title: 'Frat',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 200,
    albumCover: covers.comeup,
    description: 'Social hierarchy as punchline. Frat maps the underground onto college culture — same dynamics, different zip code.',
  },
  {
    title: 'Foamposite Interlude',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 201,
    albumCover: covers.comeup,
    description: 'An interlude that isn\'t really an interlude. Foamposites as wardrobe, mythology, and scene marker for a specific type of come-up.',
  },
  {
    title: 'My Style',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 227,
    albumCover: covers.comeup,
    description: 'The longest track on THE COMEUP. My Style is the artistic manifesto of the project — nobody else\'s blueprint, just his.',
  },
  {
    title: 'Ball Out',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 170,
    albumCover: covers.comeup,
    description: 'Spending, flexing, going all in. Ball Out is the aspirational peak of THE COMEUP — the whole project building to this moment.',
  },
  {
    title: 'Khalifa',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 180,
    albumCover: covers.comeup,
    description: 'Wiz Khalifa as aesthetic ancestor. Khalifa draws the genealogy of the smoke, the clouds, and the lo-fi rap lineage.',
  },
  {
    title: 'High',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 173,
    albumCover: covers.comeup,
    description: 'Floating. High is the drift track of THE COMEUP — everything slows down and the ceiling disappears.',
  },
  {
    title: 'Mall',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 157,
    albumCover: covers.comeup,
    description: 'Consumer culture through the underground lens. Mall is about access, display, and the status game played under fluorescent lights.',
  },
  {
    title: 'Too Gone',
    features: '[]',
    album: 'THE COMEUP',
    year: 2024,
    releaseDate: '2024-05-24',
    durationSecs: 212,
    albumCover: covers.comeup,
    description: 'Closing THE COMEUP in a haze. Too Gone is the last drift before the peak arrives — everything that follows requires this track first.',
  },

  // ─── THE PEAK (Jan 17, 2025) ─────────────────────────────────────────────
  {
    title: 'Back2Back',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 161,
    albumCover: covers.peak,
    description: 'THE PEAK opens at full speed. Back2Back doesn\'t warm up — it arrives already at the top, stacking win after win.',
  },
  {
    title: 'Icey Soles',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 198,
    albumCover: covers.peak,
    description: 'The defining track of the era. Icey Soles brought a wider audience in — sneaker imagery, pristine delivery, and a hook that doesn\'t let go.',
  },
  {
    title: 'Taipei / Waterbed',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 195,
    albumCover: covers.peak,
    description: 'Two worlds compressed into one track. Taipei\'s neon distance meets the plush domestic softness of a waterbed — contrast as texture.',
  },
  {
    title: 'Elite Socks',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 189,
    albumCover: covers.peak,
    description: 'The detail that most people miss. Elite Socks is about caring deeply about something nobody else tracks — and making it cool anyway.',
  },
  {
    title: 'Goyard',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 183,
    albumCover: covers.peak,
    description: 'The heritage luxury flex. Goyard is quiet about it — no monogram, no explanation, just the right people understanding.',
  },
  {
    title: 'Dope Love',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 188,
    albumCover: covers.peak,
    description: 'The softest title on the hardest project. Dope Love is smokedope\'s version of vulnerable — filtered through haze and restrained delivery.',
  },
  {
    title: 'Draft Night',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 140,
    albumCover: covers.peak,
    description: 'Getting selected, getting called up. Draft Night uses the NBA draft as metaphor for a moment of recognition that changes everything.',
  },
  {
    title: 'Gnarly',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 208,
    albumCover: covers.peak,
    description: 'The hardest track on THE PEAK. Gnarly arrived as a single before the album and set the tone — high energy, skate-culture adjacent, impossible to ignore.',
  },
  {
    title: 'Trust',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 156,
    albumCover: covers.peak,
    description: 'Earned, not given. Trust sits in the back half of THE PEAK as the emotional anchor — who gets access, who doesn\'t.',
  },
  {
    title: 'In Da Party',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 141,
    albumCover: covers.peak,
    description: '21M+ streams. In Da Party is THE PEAK\'s crossover moment — an instant scene-setter that hit everyone at once.',
  },
  {
    title: 'Hypebeast',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 110,
    albumCover: covers.peak,
    description: 'Under two minutes, maximum critique. Hypebeast deconstructs the culture it\'s simultaneously a part of — wearing the clothes while roasting the people who chase them.',
  },
  {
    title: 'Eastbay',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 154,
    albumCover: covers.peak,
    description: 'The catalog flip. Eastbay (the sneaker retailer) as portal to memory — ordering shoes online before it was easy, waiting for the box.',
  },
  {
    title: 'Off Tha Cid',
    features: '[]',
    album: 'THE PEAK',
    year: 2025,
    releaseDate: '2025-01-17',
    durationSecs: 137,
    albumCover: covers.peak,
    description: 'Closing THE PEAK in a blurred state. Off Tha Cid ends the album the way a peak always ends — reality dissolving at the edges.',
  },

  // ─── THE COMEDOWN (Mar 27, 2026) ─────────────────────────────────────────
  {
    title: 'banshee',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 179,
    albumCover: covers.comedown,
    description: 'A wail at the start of the end. banshee opens THE COMEDOWN with a ghost-tone — something has already passed, this is the aftermath.',
  },
  {
    title: 'My Chalice',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 192,
    albumCover: covers.comedown,
    description: 'Drinking from a vessel only you carry. My Chalice is a meditation on what costs you personally that nobody else can see.',
  },
  {
    title: "Wild 'N Out",
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 113,
    albumCover: covers.comedown,
    description: 'The shortest moment of chaos on THE COMEDOWN. Wild \'N Out is barely two minutes — a flash of energy before the weight returns.',
  },
  {
    title: 'Smoking Kills',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 144,
    albumCover: covers.comedown,
    description: 'The warning label as song title. Smoking Kills sits inside the comedown with dark irony — knowing what it costs and doing it anyway.',
  },
  {
    title: 'flocc',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 165,
    albumCover: covers.comedown,
    description: 'The flock disperses. flocc is about who stays when the peak is over — the people still there after the cameras leave.',
  },
  {
    title: 'How I Bled',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 151,
    albumCover: covers.comedown,
    description: 'Cost accounting. How I Bled traces the price of the come-up — what was spent, what was lost, what left a mark.',
  },
  {
    title: 'Forgiato',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 156,
    albumCover: covers.comedown,
    description: 'Custom wheels as symbol. Forgiato on THE COMEDOWN is a reminder of the height — flexing while falling, spinning while slowing down.',
  },
  {
    title: 'be my zombie',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 249,
    albumCover: covers.comedown,
    description: 'The centerpiece of THE COMEDOWN at four minutes. be my zombie is the most emotional track in the catalogue — asking someone to stay without really being present.',
  },
  {
    title: 'Ozweego',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 132,
    albumCover: covers.comedown,
    description: 'Adidas Ozwegos as time machine. The silhouette carries Y2K energy — wearing nostalgia while processing the present.',
  },
  {
    title: 'Famous',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 108,
    albumCover: covers.comedown,
    description: 'Under two minutes on the cost of visibility. Famous is the shortest track on THE COMEDOWN and possibly the most pointed.',
  },
  {
    title: 'lips sealed',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 182,
    albumCover: covers.comedown,
    description: 'Silence as strategy. lips sealed is about what doesn\'t get said — keeping the inner circle tight when the outside world is watching.',
  },
  {
    title: 'lay my body down',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 197,
    albumCover: covers.comedown,
    description: 'Surrender in the penultimate track. lay my body down is exhausted — not defeated, but finally resting after the full arc.',
  },
  {
    title: 'closing time',
    features: '[]',
    album: 'THE COMEDOWN',
    year: 2026,
    releaseDate: '2026-03-27',
    durationSecs: 160,
    albumCover: covers.comedown,
    description: 'The final track of the trilogy. closing time is quiet, deliberate, and complete — the lights go out on the whole come-up / peak / come-down cycle.',
  },

  // ─── Standalone Singles ───────────────────────────────────────────────────
  {
    title: 'Bleed',
    features: '[]',
    album: 'Single',
    year: 2022,
    releaseDate: '2022-02-10',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Early standalone output from before SMOKESHOP. Bleed shows the raw state — unpolished, direct, and bleeding into what came next.',
  },
  {
    title: 'SPAZZO',
    features: '[]',
    album: 'Single',
    year: 2022,
    releaseDate: '2022-04-01',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Moving erratically, on purpose. SPAZZO is an early single that captures the scattered, kinetic energy before the first tape.',
  },
  {
    title: 'Pink Dolphin',
    features: '[]',
    album: 'Single',
    year: 2022,
    releaseDate: '2022-06-01',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Rare by design. Pink Dolphin — the streetwear brand, the mythical animal — frames rarity as the ultimate flex.',
  },
  {
    title: 'Hi As Hell',
    features: '["Salvador"]',
    album: 'Single',
    year: 2022,
    releaseDate: '2022-07-26',
    durationSecs: 126,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Ceiling-less. Hi As Hell with Salvador is a collab built entirely around altitude — the beat, the energy, and the state of mind all peak together.',
  },
  {
    title: 'ONNA SHIRT',
    features: '[]',
    album: 'Single',
    year: 2022,
    releaseDate: '2022-10-01',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'The fit as identity card. ONNA SHIRT is about wearing your whole aesthetic — who you are walks in before you do.',
  },
  {
    title: 'Halo',
    features: '["Shadow Wizard Money Gang"]',
    album: 'Single',
    year: 2023,
    releaseDate: '2023-03-01',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Blessed from above with Shadow Wizard Money Gang. Halo blends cloud-rap spirituality with the collective\'s chaotic-good energy.',
  },
  {
    title: 'Warzone',
    features: '[]',
    album: 'Single',
    year: 2023,
    releaseDate: '2023-03-17',
    durationSecs: 154,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Everything is contested. Warzone maps the underground rap space as a combat zone — staying sharp or getting taken out.',
  },
  {
    title: 'SAY IT AINT DRO',
    features: '[]',
    album: 'Single',
    year: 2023,
    releaseDate: '2023-03-17',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Denial with swagger. SAY IT AINT DRO is a standoff — pressure to label, refusal to fold.',
  },
  {
    title: 'Take My Life',
    features: '["UAV"]',
    album: 'Single',
    year: 2023,
    releaseDate: '2023-06-01',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'A collaborative single with UAV. Take My Life pushes into more dramatic sonic territory — stakes raised, production darker.',
  },
  {
    title: 'CR4ZY',
    features: '[]',
    album: 'Single',
    year: 2023,
    releaseDate: '2023-09-01',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'The number replaces the letter — intentional misspelling as aesthetic choice. CR4ZY is about operating outside normal parameters.',
  },
  {
    title: 'Sleep',
    features: '["Nokia Angel"]',
    album: 'Single',
    year: 2024,
    releaseDate: '2024-03-29',
    durationSecs: 155,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Rest as luxury. Sleep with Nokia Angel is the most serene collab in the catalogue — both artists at their most unhurried.',
  },
  {
    title: 'It Aint Nun',
    features: '["CHRIST DILLINGER", "Acid Souljah", "DJ Smokey", "Xhris2Eazy"]',
    album: 'Single',
    year: 2024,
    releaseDate: '2024-09-12',
    durationSecs: 269,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'The biggest collab in the catalogue. It Aint Nun pulls together smokedope, CHRIST DILLINGER, Acid Souljah, DJ Smokey, and Xhris2Eazy — produced by 808 Mafia, maximal energy.',
  },
  {
    title: '2016LYFE',
    features: '[]',
    album: 'Single',
    year: 2025,
    releaseDate: '2025-09-12',
    durationSecs: 215,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'A return to the name, the year, the whole origin story. 2016LYFE connects post-trilogy smokedope back to where the project started.',
  },
  {
    title: 'Buff',
    features: '["Hackle"]',
    album: 'Single',
    year: 2025,
    releaseDate: '2025-07-04',
    durationSecs: 232,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Strength and shine. Buff with Hackle is post-trilogy output — the era after the trilogy where the sound keeps evolving.',
  },
  {
    title: 'Flounder',
    features: '[]',
    album: 'Single',
    year: 2025,
    releaseDate: '2025-11-21',
    durationSecs: 150,
    albumCover: 'https://cdn-images.dzcdn.net/images/cover/d41d8cd98f00b204e9800998ecf8427e/640x640-000000-80-0-0.jpg',
    description: 'Moving without direction, finding it anyway. Flounder is one of the last 2025 singles — uncertain motion becoming purposeful.',
  },
];

async function main() {
  for (const song of songs) {
    const songSlug = slug(song.title);
    await prisma.song.upsert({
      where: { slug: songSlug },
      update: {},
      create: {
        slug: songSlug,
        title: song.title,
        features: song.features,
        album: song.album,
        year: song.year,
        releaseDate: song.releaseDate,
        durationSecs: song.durationSecs,
        singleCover: song.singleCover ?? null,
        albumCover: song.albumCover,
        description: song.description,
      },
    });
  }
  console.log(`Seeded ${songs.length} songs.`);
}

main()
  .catch(console.error)
  .finally(() => prisma.$disconnect());
